[phases.setup]
nixPkgs = ['nodejs-20_x', 'python3']

[phases.install]
cmds = [
  'npm ci',
  'npx playwright install-deps chromium',
  'npx playwright install chromium'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
