[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = [
  'npm ci',
  'npx prisma generate --schema=apps/api/prisma/schema.prisma',
  'npx playwright install-deps chromium',
  'npx playwright install chromium'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
